version: '3'

services:
  neo4j:
    container_name: '${COMPOSE_PROJECT_NAME}-neo4j'
    image: neo4j:${NEO4J_IMAGE_VERSION}
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    volumes:
      - ${HOST_NEO4J_DATA_DIR}:${CONTAINER_NEO4J_DATA_DIR}
      - ${HOST_NEO4J_LOG_DIR}:${CONTAINER_NEO4J_LOG_DIR}
    ports:
      - ${NEO4J_BROWSER_PORT}:7474
      - ${NEO4J_PORT}:7687
